name: Docker CiCd

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: docker login
              env:
                  DOCKER_USER: ${{ secrets.DOCKER_USER }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
              run: |
                  docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

            - name: docker build frontend
              run: |
                  docker build -t brandodev/frontend ./frontend

            - name: docker build backend
              run: docker build -t brandodev/backend ./backend

            - name: docker push
              run: |
                  docker push brandodev/frontend
                  docker push brandodev/backend

            - name: pull from github
            - run:
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.USER }}
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      cd ~/app/demo && git pull
                      cd ~app/demo/devops
                      docker-compose down
                      docker rmi $(docker images ps -q)
                      docker-compose up -d --build
